#global properties
project:
  name: @project.name@
  version: @project.version@
  description: @project.description@
spring:
  profiles:
    active: "dev"
server:
  port: 8080
endpoints:
  shutdown:
    enabled: false
    sensitive: false
management:
  context-path: /management
  security:
    enabled: false
quandl:
  api:
    endpoint: 'https://www.quandl.com/api/v3/datatables/WIKI/PRICES.csv?ticker=COF,GOOGL,MSFT&date.gte=2017-01-01&date.lte=2017-06-30&api_key=s-GMZ_xkw6CrkGYUWs1p'
---
spring:
  profiles: "dev"
server:
  context-path: /cofi-coding-exercise
---
spring:
  profiles: prod
server:
  context-path: /